### ISSUE TITLE
Code crashes

### ISSUE THREAD

**Issue by rinirikhil** [jlhernando/url-inspector-automator-js#1]
![image](https://user-images.githubusercontent.com/86122236/122594148-42359380-d084-11eb-9d53-591389f17e49.png)
Getting below error when running the code. I am an SEO person, and I am new to python. Could you please help me with this. One of tghe selectors seems to be not working

node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.evaluate: Evaluation failed: document.querySelector(...) is null
@debugger eval code line 307 > eval:1:17
callFunction@debugger eval code:308:28
@debugger eval code:1:44

**Comment by jlhernando** [comment]
Thanks for flagging the issue @rinirikhil. One of the selectors to extract info wasn't working anymore and I have now updated it.

Just update the script to the latest version and it should work fine.
