### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by DesignerApparelSales** [jlhernando/url-inspector-automator-js#2]
Hi, I'm getting error "Evaluation failed: document.querySelector(...) is null"  does it still work? I think the error happen here document.querySelector('.OJb48e').textContent. Also can I do something about the 2-factor authentication, its a pain that i have to keep on doing it everytime i run the code. thanks for the good work.

**Comment by jlhernando** [comment]
Hi, I've stopped updating this repo since Google released their Index status API endpoint that allows to get info for 2000 URLs/day which is more than the 100 you would get from the URL Inspection tool.

You can download the repo to access this API here: https://github.com/jlhernando/google-index-inspect-api

I'd recommend to use the API endpoint as you will get more data but you still find valuable the URL Inspection Tool let me know and I'll do an update.

Thanks,
Jose

**Comment by DesignerApparelSales** [comment]
Hi, Thanks for your response. I use this so that I can manually add my url to " request indexing"  , I currently have 170k url that is "Discovered - currently not indexed",  11k "Crawled - currently not indexed" and only 500 url "Submitted and indexed" , it have been like this for over 2 years. The only thing that work is for me to manually request indexing. So that is why i was looking for an automation to do it instead of me doing it myself.  I have try this https://www.jcchouinard.com/google-indexing-api-with-python/ but it doesn't seem to work either. Does your new repo do request indexing in batch? Can you get this repo to be able to automate a url inspection and then request indexing for each url.  this is my site, https://designerapparelsales.com/  I need to index my item pages so people can search for it. I have over 300k pages.

**Comment by jlhernando** [comment]
At the moment this feature is not available through the script. However, I believe there is a limit of 10 requests per daqy and per property to use it. In your case it might be a bit of an uphill battle so not sure if this is the best way to do it.

Have you looked into the Indexing API? (https://developers.google.com/search/apis/indexing-api/v3/quickstart). In principle it's only for Jobs and Events but I've seen cases of SEOs using it for other types of pages and it seems to work.

I've found 2 repos that might be able to help you here:
- https://github.com/swalker-888/google-indexing-api-bulk
- https://github.com/m3m3nto/giaa

Haven't tried them myself so not sure if they work but I think it might be worth trying.

**Comment by DesignerApparelSales** [comment]
Its appeared the index api does work. I just got 200 more urls indexed today from  using it, that is more than I had for months. Thank you for your help!

**Comment by albertolive** [comment]
@DesignerApparelSales, which one did you end up using?
